import { Language } from './types';

export const AVAILABLE_LANGUAGES: Language[] = [
    { code: 'af', name: 'Afrikaans', flagCode: 'za' },
    { code: 'sq', name: 'Albanian', flagCode: 'al' },
    { code: 'ar', name: 'Arabic', flagCode: 'sa' },
    { code: 'hy', name: 'Armenian', flagCode: 'am' },
    { code: 'az', name: 'Azerbaijani' },
    { code: 'eu', name: 'Basque', flagCode: 'es' },
    { code: 'be', name: 'Belarusian', flagCode: 'by' },
    { code: 'bn', name: 'Bengali', flagCode: 'bd' },
    { code: 'bs', name: 'Bosnian', flagCode: 'ba' },
    { code: 'bg', name: 'Bulgarian' },
    { code: 'ca', name: 'Catalan', flagCode: 'es' },
    { code: 'zh', name: 'Chinese', flagCode: 'cn' },
    { code: 'hr', name: 'Croatian' },
    { code: 'cs', name: 'Czech', flagCode: 'cz' },
    { code: 'da', name: 'Danish', flagCode: 'dk' },
    { code: 'nl', name: 'Dutch' },
    { code: 'en', name: 'English', flagCode: 'gb' },
    { code: 'et', name: 'Estonian', flagCode: 'ee' },
    { code: 'fi', name: 'Finnish' },
    { code: 'fr', name: 'French' },
    { code: 'gl', name: 'Galician', flagCode: 'es' },
    { code: 'ka', name: 'Georgian', flagCode: 'ge' },
    { code: 'de', name: 'German' },
    { code: 'el', name: 'Greek', flagCode: 'gr' },
    { code: 'gu', name: 'Gujarati', flagCode: 'in' },
    { code: 'he', name: 'Hebrew', flagCode: 'il' },
    { code: 'hi', name: 'Hindi', flagCode: 'in' },
    { code: 'hu', name: 'Hungarian' },
    { code: 'is', name: 'Icelandic' },
    { code: 'id', name: 'Indonesian' },
    { code: 'ga', name: 'Irish', flagCode: 'ie' },
    { code: 'it', name: 'Italian' },
    { code: 'ja', name: 'Japanese', flagCode: 'jp' },
    { code: 'kn', name: 'Kannada', flagCode: 'in' },
    { code: 'kk', name: 'Kazakh', flagCode: 'kz' },
    { code: 'km', name: 'Khmer', flagCode: 'kh' },
    { code: 'ko', name: 'Korean', flagCode: 'kr' },
    { code: 'ky', name: 'Kyrgyz', flagCode: 'kg' },
    { code: 'lo', name: 'Lao', flagCode: 'la' },
    { code: 'lv', name: 'Latvian' },
    { code: 'lt', name: 'Lithuanian' },
    { code: 'mk', name: 'Macedonian' },
    { code: 'ms', name: 'Malay', flagCode: 'my' },
    { code: 'ml', name: 'Malayalam', flagCode: 'in' },
    { code: 'mt', name: 'Maltese' },
    { code: 'mi', name: 'Maori', flagCode: 'nz' },
    { code: 'mr', name: 'Marathi', flagCode: 'in' },
    { code: 'mn', name: 'Mongolian' },
    { code: 'ne', name: 'Nepali', flagCode: 'np' },
    { code: 'no', name: 'Norwegian' },
    { code: 'fa', name: 'Persian', flagCode: 'ir' },
    { code: 'pl', name: 'Polish' },
    { code: 'pt', name: 'Portuguese' },
    { code: 'pa', name: 'Punjabi', flagCode: 'in' },
    { code: 'ro', name: 'Romanian' },
    { code: 'ru', name: 'Russian' },
    { code: 'sr', name: 'Serbian', flagCode: 'rs' },
    { code: 'si', name: 'Sinhala', flagCode: 'lk' },
    { code: 'sk', name: 'Slovak' },
    { code: 'sl', name: 'Slovenian', flagCode: 'si' },
    { code: 'es', name: 'Spanish' },
    { code: 'sw', name: 'Swahili', flagCode: 'ke' },
    { code: 'sv', name: 'Swedish', flagCode: 'se' },
    { code: 'ta', name: 'Tamil', flagCode: 'in' },
    { code: 'te', name: 'Telugu', flagCode: 'in' },
    { code: 'th', name: 'Thai' },
    { code: 'tr', name: 'Turkish' },
    { code: 'uk', name: 'Ukrainian', flagCode: 'ua' },
    { code: 'ur', name: 'Urdu', flagCode: 'pk' },
    { code: 'uz', name: 'Uzbek' },
    { code: 'vi', name: 'Vietnamese', flagCode: 'vn' },
    { code: 'cy', name: 'Welsh', flagCode: 'gb' },
];

export const TONES = ['Formal', 'Informal', 'Playful', 'Technical', 'Marketing'];

const langToFlagMap = new Map(AVAILABLE_LANGUAGES.map(lang => [lang.code, lang.flagCode || lang.code]));

export const getFlagCode = (langCode: string): string => {
    return langToFlagMap.get(langCode) || langCode;
};

export const ApiKeyPermissions = Object.freeze({
    ReadOnly: 'readonly',
    Edit: 'edit',
    Admin: 'admin',
});